# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/briggsjt/WORKING/Pickett

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/briggsjt/WORKING/Pickett

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/briggsjt/WORKING/Pickett/CMakeFiles /home/briggsjt/WORKING/Pickett//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/briggsjt/WORKING/Pickett/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spfit

# Build rule for target.
spfit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spfit
.PHONY : spfit

# fast build rule for target.
spfit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/build
.PHONY : spfit/fast

#=============================================================================
# Target rules for targets named spcat

# Build rule for target.
spcat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spcat
.PHONY : spcat

# fast build rule for target.
spcat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/build
.PHONY : spcat/fast

CalCat.o: CalCat.cpp.o
.PHONY : CalCat.o

# target to build an object file
CalCat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat.cpp.o
.PHONY : CalCat.cpp.o

CalCat.i: CalCat.cpp.i
.PHONY : CalCat.i

# target to preprocess a source file
CalCat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat.cpp.i
.PHONY : CalCat.cpp.i

CalCat.s: CalCat.cpp.s
.PHONY : CalCat.s

# target to generate assembly for a file
CalCat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat.cpp.s
.PHONY : CalCat.cpp.s

CalCatIO.o: CalCatIO.cpp.o
.PHONY : CalCatIO.o

# target to build an object file
CalCatIO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCatIO.cpp.o
.PHONY : CalCatIO.cpp.o

CalCatIO.i: CalCatIO.cpp.i
.PHONY : CalCatIO.i

# target to preprocess a source file
CalCatIO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCatIO.cpp.i
.PHONY : CalCatIO.cpp.i

CalCatIO.s: CalCatIO.cpp.s
.PHONY : CalCatIO.s

# target to generate assembly for a file
CalCatIO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCatIO.cpp.s
.PHONY : CalCatIO.cpp.s

CalCat_helpers.o: CalCat_helpers.cpp.o
.PHONY : CalCat_helpers.o

# target to build an object file
CalCat_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat_helpers.cpp.o
.PHONY : CalCat_helpers.cpp.o

CalCat_helpers.i: CalCat_helpers.cpp.i
.PHONY : CalCat_helpers.i

# target to preprocess a source file
CalCat_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat_helpers.cpp.i
.PHONY : CalCat_helpers.cpp.i

CalCat_helpers.s: CalCat_helpers.cpp.s
.PHONY : CalCat_helpers.s

# target to generate assembly for a file
CalCat_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/CalCat_helpers.cpp.s
.PHONY : CalCat_helpers.cpp.s

CalFit.o: CalFit.cpp.o
.PHONY : CalFit.o

# target to build an object file
CalFit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit.cpp.o
.PHONY : CalFit.cpp.o

CalFit.i: CalFit.cpp.i
.PHONY : CalFit.i

# target to preprocess a source file
CalFit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit.cpp.i
.PHONY : CalFit.cpp.i

CalFit.s: CalFit.cpp.s
.PHONY : CalFit.s

# target to generate assembly for a file
CalFit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit.cpp.s
.PHONY : CalFit.cpp.s

CalFitIO.o: CalFitIO.cpp.o
.PHONY : CalFitIO.o

# target to build an object file
CalFitIO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFitIO.cpp.o
.PHONY : CalFitIO.cpp.o

CalFitIO.i: CalFitIO.cpp.i
.PHONY : CalFitIO.i

# target to preprocess a source file
CalFitIO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFitIO.cpp.i
.PHONY : CalFitIO.cpp.i

CalFitIO.s: CalFitIO.cpp.s
.PHONY : CalFitIO.s

# target to generate assembly for a file
CalFitIO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFitIO.cpp.s
.PHONY : CalFitIO.cpp.s

CalFit_helpers.o: CalFit_helpers.cpp.o
.PHONY : CalFit_helpers.o

# target to build an object file
CalFit_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit_helpers.cpp.o
.PHONY : CalFit_helpers.cpp.o

CalFit_helpers.i: CalFit_helpers.cpp.i
.PHONY : CalFit_helpers.i

# target to preprocess a source file
CalFit_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit_helpers.cpp.i
.PHONY : CalFit_helpers.cpp.i

CalFit_helpers.s: CalFit_helpers.cpp.s
.PHONY : CalFit_helpers.s

# target to generate assembly for a file
CalFit_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/CalFit_helpers.cpp.s
.PHONY : CalFit_helpers.cpp.s

DpiEngine.o: DpiEngine.cpp.o
.PHONY : DpiEngine.o

# target to build an object file
DpiEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/DpiEngine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/DpiEngine.cpp.o
.PHONY : DpiEngine.cpp.o

DpiEngine.i: DpiEngine.cpp.i
.PHONY : DpiEngine.i

# target to preprocess a source file
DpiEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/DpiEngine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/DpiEngine.cpp.i
.PHONY : DpiEngine.cpp.i

DpiEngine.s: DpiEngine.cpp.s
.PHONY : DpiEngine.s

# target to generate assembly for a file
DpiEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/DpiEngine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/DpiEngine.cpp.s
.PHONY : DpiEngine.cpp.s

Logger.o: Logger.cpp.o
.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/Logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i
.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/Logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s
.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/Logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

SigintFlag.o: SigintFlag.cpp.o
.PHONY : SigintFlag.o

# target to build an object file
SigintFlag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SigintFlag.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SigintFlag.cpp.o
.PHONY : SigintFlag.cpp.o

SigintFlag.i: SigintFlag.cpp.i
.PHONY : SigintFlag.i

# target to preprocess a source file
SigintFlag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SigintFlag.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SigintFlag.cpp.i
.PHONY : SigintFlag.cpp.i

SigintFlag.s: SigintFlag.cpp.s
.PHONY : SigintFlag.s

# target to generate assembly for a file
SigintFlag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SigintFlag.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SigintFlag.cpp.s
.PHONY : SigintFlag.cpp.s

SpinvEngine.o: SpinvEngine.cpp.o
.PHONY : SpinvEngine.o

# target to build an object file
SpinvEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SpinvEngine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SpinvEngine.cpp.o
.PHONY : SpinvEngine.cpp.o

SpinvEngine.i: SpinvEngine.cpp.i
.PHONY : SpinvEngine.i

# target to preprocess a source file
SpinvEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SpinvEngine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SpinvEngine.cpp.i
.PHONY : SpinvEngine.cpp.i

SpinvEngine.s: SpinvEngine.cpp.s
.PHONY : SpinvEngine.s

# target to generate assembly for a file
SpinvEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/SpinvEngine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/SpinvEngine.cpp.s
.PHONY : SpinvEngine.cpp.s

cat_main.o: cat_main.cpp.o
.PHONY : cat_main.o

# target to build an object file
cat_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cat_main.cpp.o
.PHONY : cat_main.cpp.o

cat_main.i: cat_main.cpp.i
.PHONY : cat_main.i

# target to preprocess a source file
cat_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cat_main.cpp.i
.PHONY : cat_main.cpp.i

cat_main.s: cat_main.cpp.s
.PHONY : cat_main.s

# target to generate assembly for a file
cat_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cat_main.cpp.s
.PHONY : cat_main.cpp.s

catutil.o: catutil.c.o
.PHONY : catutil.o

# target to build an object file
catutil.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/catutil.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/catutil.c.o
.PHONY : catutil.c.o

catutil.i: catutil.c.i
.PHONY : catutil.i

# target to preprocess a source file
catutil.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/catutil.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/catutil.c.i
.PHONY : catutil.c.i

catutil.s: catutil.c.s
.PHONY : catutil.s

# target to generate assembly for a file
catutil.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/catutil.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/catutil.c.s
.PHONY : catutil.c.s

cnjj.o: cnjj.c.o
.PHONY : cnjj.o

# target to build an object file
cnjj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/cnjj.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cnjj.c.o
.PHONY : cnjj.c.o

cnjj.i: cnjj.c.i
.PHONY : cnjj.i

# target to preprocess a source file
cnjj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/cnjj.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cnjj.c.i
.PHONY : cnjj.c.i

cnjj.s: cnjj.c.s
.PHONY : cnjj.s

# target to generate assembly for a file
cnjj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/cnjj.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/cnjj.c.s
.PHONY : cnjj.c.s

dblas.o: dblas.c.o
.PHONY : dblas.o

# target to build an object file
dblas.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dblas.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dblas.c.o
.PHONY : dblas.c.o

dblas.i: dblas.c.i
.PHONY : dblas.i

# target to preprocess a source file
dblas.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dblas.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dblas.c.i
.PHONY : dblas.c.i

dblas.s: dblas.c.s
.PHONY : dblas.s

# target to generate assembly for a file
dblas.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dblas.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dblas.c.s
.PHONY : dblas.c.s

dpi.o: dpi.cpp.o
.PHONY : dpi.o

# target to build an object file
dpi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dpi.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dpi.cpp.o
.PHONY : dpi.cpp.o

dpi.i: dpi.cpp.i
.PHONY : dpi.i

# target to preprocess a source file
dpi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dpi.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dpi.cpp.i
.PHONY : dpi.cpp.i

dpi.s: dpi.cpp.s
.PHONY : dpi.s

# target to generate assembly for a file
dpi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/dpi.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/dpi.cpp.s
.PHONY : dpi.cpp.s

file_helpers.o: file_helpers.cpp.o
.PHONY : file_helpers.o

# target to build an object file
file_helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/file_helpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/file_helpers.cpp.o
.PHONY : file_helpers.cpp.o

file_helpers.i: file_helpers.cpp.i
.PHONY : file_helpers.i

# target to preprocess a source file
file_helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/file_helpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/file_helpers.cpp.i
.PHONY : file_helpers.cpp.i

file_helpers.s: file_helpers.cpp.s
.PHONY : file_helpers.s

# target to generate assembly for a file
file_helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/file_helpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/file_helpers.cpp.s
.PHONY : file_helpers.cpp.s

fit_main.o: fit_main.cpp.o
.PHONY : fit_main.o

# target to build an object file
fit_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/fit_main.cpp.o
.PHONY : fit_main.cpp.o

fit_main.i: fit_main.cpp.i
.PHONY : fit_main.i

# target to preprocess a source file
fit_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/fit_main.cpp.i
.PHONY : fit_main.cpp.i

fit_main.s: fit_main.cpp.s
.PHONY : fit_main.s

# target to generate assembly for a file
fit_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/fit_main.cpp.s
.PHONY : fit_main.cpp.s

ftran.o: ftran.c.o
.PHONY : ftran.o

# target to build an object file
ftran.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ftran.c.o
.PHONY : ftran.c.o

ftran.i: ftran.c.i
.PHONY : ftran.i

# target to preprocess a source file
ftran.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ftran.c.i
.PHONY : ftran.c.i

ftran.s: ftran.c.s
.PHONY : ftran.s

# target to generate assembly for a file
ftran.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ftran.c.s
.PHONY : ftran.c.s

lsqfit.o: lsqfit.c.o
.PHONY : lsqfit.o

# target to build an object file
lsqfit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/lsqfit.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/lsqfit.c.o
.PHONY : lsqfit.c.o

lsqfit.i: lsqfit.c.i
.PHONY : lsqfit.i

# target to preprocess a source file
lsqfit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/lsqfit.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/lsqfit.c.i
.PHONY : lsqfit.c.i

lsqfit.s: lsqfit.c.s
.PHONY : lsqfit.s

# target to generate assembly for a file
lsqfit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/lsqfit.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/lsqfit.c.s
.PHONY : lsqfit.c.s

sortsub.o: sortsub.c.o
.PHONY : sortsub.o

# target to build an object file
sortsub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/sortsub.c.o
.PHONY : sortsub.c.o

sortsub.i: sortsub.c.i
.PHONY : sortsub.i

# target to preprocess a source file
sortsub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/sortsub.c.i
.PHONY : sortsub.c.i

sortsub.s: sortsub.c.s
.PHONY : sortsub.s

# target to generate assembly for a file
sortsub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/sortsub.c.s
.PHONY : sortsub.c.s

spinit.o: spinit.cpp.o
.PHONY : spinit.o

# target to build an object file
spinit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinit.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinit.cpp.o
.PHONY : spinit.cpp.o

spinit.i: spinit.cpp.i
.PHONY : spinit.i

# target to preprocess a source file
spinit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinit.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinit.cpp.i
.PHONY : spinit.cpp.i

spinit.s: spinit.cpp.s
.PHONY : spinit.s

# target to generate assembly for a file
spinit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinit.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinit.cpp.s
.PHONY : spinit.cpp.s

spinv_hamiltonian.o: spinv_hamiltonian.cpp.o
.PHONY : spinv_hamiltonian.o

# target to build an object file
spinv_hamiltonian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_hamiltonian.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_hamiltonian.cpp.o
.PHONY : spinv_hamiltonian.cpp.o

spinv_hamiltonian.i: spinv_hamiltonian.cpp.i
.PHONY : spinv_hamiltonian.i

# target to preprocess a source file
spinv_hamiltonian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_hamiltonian.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_hamiltonian.cpp.i
.PHONY : spinv_hamiltonian.cpp.i

spinv_hamiltonian.s: spinv_hamiltonian.cpp.s
.PHONY : spinv_hamiltonian.s

# target to generate assembly for a file
spinv_hamiltonian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_hamiltonian.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_hamiltonian.cpp.s
.PHONY : spinv_hamiltonian.cpp.s

spinv_linalg_sort.o: spinv_linalg_sort.c.o
.PHONY : spinv_linalg_sort.o

# target to build an object file
spinv_linalg_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_linalg_sort.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_linalg_sort.c.o
.PHONY : spinv_linalg_sort.c.o

spinv_linalg_sort.i: spinv_linalg_sort.c.i
.PHONY : spinv_linalg_sort.i

# target to preprocess a source file
spinv_linalg_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_linalg_sort.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_linalg_sort.c.i
.PHONY : spinv_linalg_sort.c.i

spinv_linalg_sort.s: spinv_linalg_sort.c.s
.PHONY : spinv_linalg_sort.s

# target to generate assembly for a file
spinv_linalg_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_linalg_sort.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_linalg_sort.c.s
.PHONY : spinv_linalg_sort.c.s

spinv_setup.o: spinv_setup.cpp.o
.PHONY : spinv_setup.o

# target to build an object file
spinv_setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_setup.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_setup.cpp.o
.PHONY : spinv_setup.cpp.o

spinv_setup.i: spinv_setup.cpp.i
.PHONY : spinv_setup.i

# target to preprocess a source file
spinv_setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_setup.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_setup.cpp.i
.PHONY : spinv_setup.cpp.i

spinv_setup.s: spinv_setup.cpp.s
.PHONY : spinv_setup.s

# target to generate assembly for a file
spinv_setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_setup.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_setup.cpp.s
.PHONY : spinv_setup.cpp.s

spinv_spin_symmetry.o: spinv_spin_symmetry.cpp.o
.PHONY : spinv_spin_symmetry.o

# target to build an object file
spinv_spin_symmetry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_spin_symmetry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_spin_symmetry.cpp.o
.PHONY : spinv_spin_symmetry.cpp.o

spinv_spin_symmetry.i: spinv_spin_symmetry.cpp.i
.PHONY : spinv_spin_symmetry.i

# target to preprocess a source file
spinv_spin_symmetry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_spin_symmetry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_spin_symmetry.cpp.i
.PHONY : spinv_spin_symmetry.cpp.i

spinv_spin_symmetry.s: spinv_spin_symmetry.cpp.s
.PHONY : spinv_spin_symmetry.s

# target to generate assembly for a file
spinv_spin_symmetry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_spin_symmetry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_spin_symmetry.cpp.s
.PHONY : spinv_spin_symmetry.cpp.s

spinv_utils.o: spinv_utils.cpp.o
.PHONY : spinv_utils.o

# target to build an object file
spinv_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_utils.cpp.o
.PHONY : spinv_utils.cpp.o

spinv_utils.i: spinv_utils.cpp.i
.PHONY : spinv_utils.i

# target to preprocess a source file
spinv_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_utils.cpp.i
.PHONY : spinv_utils.cpp.i

spinv_utils.s: spinv_utils.cpp.s
.PHONY : spinv_utils.s

# target to generate assembly for a file
spinv_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/spinv_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/spinv_utils.cpp.s
.PHONY : spinv_utils.cpp.s

subfit.o: subfit.cpp.o
.PHONY : subfit.o

# target to build an object file
subfit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/subfit.cpp.o
.PHONY : subfit.cpp.o

subfit.i: subfit.cpp.i
.PHONY : subfit.i

# target to preprocess a source file
subfit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/subfit.cpp.i
.PHONY : subfit.cpp.i

subfit.s: subfit.cpp.s
.PHONY : subfit.s

# target to generate assembly for a file
subfit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/subfit.cpp.s
.PHONY : subfit.cpp.s

ulib.o: ulib.c.o
.PHONY : ulib.o

# target to build an object file
ulib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ulib.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/ulib.c.o
.PHONY : ulib.c.o

ulib.i: ulib.c.i
.PHONY : ulib.i

# target to preprocess a source file
ulib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ulib.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/ulib.c.i
.PHONY : ulib.c.i

ulib.s: ulib.c.s
.PHONY : ulib.s

# target to generate assembly for a file
ulib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spfit.dir/build.make CMakeFiles/spfit.dir/ulib.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/spcat.dir/build.make CMakeFiles/spcat.dir/ulib.c.s
.PHONY : ulib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... spcat"
	@echo "... spfit"
	@echo "... CalCat.o"
	@echo "... CalCat.i"
	@echo "... CalCat.s"
	@echo "... CalCatIO.o"
	@echo "... CalCatIO.i"
	@echo "... CalCatIO.s"
	@echo "... CalCat_helpers.o"
	@echo "... CalCat_helpers.i"
	@echo "... CalCat_helpers.s"
	@echo "... CalFit.o"
	@echo "... CalFit.i"
	@echo "... CalFit.s"
	@echo "... CalFitIO.o"
	@echo "... CalFitIO.i"
	@echo "... CalFitIO.s"
	@echo "... CalFit_helpers.o"
	@echo "... CalFit_helpers.i"
	@echo "... CalFit_helpers.s"
	@echo "... DpiEngine.o"
	@echo "... DpiEngine.i"
	@echo "... DpiEngine.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... SigintFlag.o"
	@echo "... SigintFlag.i"
	@echo "... SigintFlag.s"
	@echo "... SpinvEngine.o"
	@echo "... SpinvEngine.i"
	@echo "... SpinvEngine.s"
	@echo "... cat_main.o"
	@echo "... cat_main.i"
	@echo "... cat_main.s"
	@echo "... catutil.o"
	@echo "... catutil.i"
	@echo "... catutil.s"
	@echo "... cnjj.o"
	@echo "... cnjj.i"
	@echo "... cnjj.s"
	@echo "... dblas.o"
	@echo "... dblas.i"
	@echo "... dblas.s"
	@echo "... dpi.o"
	@echo "... dpi.i"
	@echo "... dpi.s"
	@echo "... file_helpers.o"
	@echo "... file_helpers.i"
	@echo "... file_helpers.s"
	@echo "... fit_main.o"
	@echo "... fit_main.i"
	@echo "... fit_main.s"
	@echo "... ftran.o"
	@echo "... ftran.i"
	@echo "... ftran.s"
	@echo "... lsqfit.o"
	@echo "... lsqfit.i"
	@echo "... lsqfit.s"
	@echo "... sortsub.o"
	@echo "... sortsub.i"
	@echo "... sortsub.s"
	@echo "... spinit.o"
	@echo "... spinit.i"
	@echo "... spinit.s"
	@echo "... spinv_hamiltonian.o"
	@echo "... spinv_hamiltonian.i"
	@echo "... spinv_hamiltonian.s"
	@echo "... spinv_linalg_sort.o"
	@echo "... spinv_linalg_sort.i"
	@echo "... spinv_linalg_sort.s"
	@echo "... spinv_setup.o"
	@echo "... spinv_setup.i"
	@echo "... spinv_setup.s"
	@echo "... spinv_spin_symmetry.o"
	@echo "... spinv_spin_symmetry.i"
	@echo "... spinv_spin_symmetry.s"
	@echo "... spinv_utils.o"
	@echo "... spinv_utils.i"
	@echo "... spinv_utils.s"
	@echo "... subfit.o"
	@echo "... subfit.i"
	@echo "... subfit.s"
	@echo "... ulib.o"
	@echo "... ulib.i"
	@echo "... ulib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

